### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Ruta-Dsp** [Smoren/huawei-ubuntu-sound-fix#1]
Hi I am new to linux, I tried to install Ubuntu 22 distro and I have exactly the problem you described,
I tried your solution (after a lot of other commands, too many to remember) but nothing seems to have changed. :(

**Comment by Ruta-Dsp** [comment]
This is my environment:
Kernel: 6.2.0-26-generic x86_64 bits: 64
    Desktop: GNOME 42.9 Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: HUAWEI product: NBD-WXX9 v: M1010
    serial: <superuser required>
  Mobo: HUAWEI model: NBD-WXX9-PCB-B3 v: M1010 serial: <superuser required>
    UEFI: HUAWEI v: 2.31 date: 11/02/2022

In the sound option still see only "Dummy output"

**Comment by tikhcloud** [comment]
@Ruta-Dsp You have Matebook d14, this is fix for Matebook 14s

Your problem has nothing to do with the one being discussed [here](https://github.com/thesofproject/linux/issues/3350#issue-1087211497)
