### ISSUE TITLE
PipeWire support

### ISSUE THREAD

**Issue by dontknowhy** [Smoren/huawei-ubuntu-sound-fix#18]
> [PipeWire](https://www.pipewire.org/) is a project that aims to greatly improve handling of audio and video under Linux. It provides a low-latency, graph-based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both PulseAudio and JACK. PipeWire was designed with a powerful security model that makes interacting with audio and video devices from containerized applications easy, with support for Flatpak applications being the primary goal. Alongside Wayland and Flatpak, we expect PipeWire to provide a core building block for the future of Linux application development.

I have already switched to PipeWire a long time ago. But the `pacmd set-sink-port alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink "[Out] Headphones"` can't support PipeWire because there isn't real PulseAudio daemon running.
It is **not** a serious issue but it's better to support it because the PipeWire is getting more and more popular.

**Comment by Smoren** [comment]
Thank you for you issue. You can implement PipeWire support to this fix and make a PR if you want :)

**Comment by KainTim** [comment]
Should this issue be closed now that the merge request implementing this has been merged (#13)?

**Comment by Smoren** [comment]
Completed with release: https://github.com/Smoren/huawei-ubuntu-sound-fix/releases/tag/v1.3.1
