### ISSUE TITLE
Ubuntu 23.10 support

### ISSUE THREAD

**Issue by vimmerru** [Smoren/huawei-ubuntu-sound-fix#3]
Hi, the fix is working for 23.4, but for some reason it can't enable speaker on 23.10. Switching to jack seems works reliable.

**Comment by KharLexis** [comment]
> Hi, the fix is working for 23.4, but for some reason it can't enable speaker on 23.10. Switching to jack seems works reliable.

Hi, I'm having the same problem, have you been able to solve it?

**Comment by vimmerru** [comment]
> Hi, I'm having the same problem, have you been able to solve it?

Unfortunately, not. I found few workarounds that allow me to work efficiently

1. I bought $8 3.5 to usb-c adapter for my headphones that works well
2. In rarely cases i need speakers i open alsamixer and unmute headphones channel manually. It gives loud enough and acceptable sound from 2 speakers.

**Comment by vimmerru** [comment]
@KharLexis seems, i found the issue. On modern distros `amixer` command always requires the argument. Changing `amixer` to `amixer -c 0` in huawei-soundcard-headphones-monitor.sh solved the problem. 

I tested it on Debian 12, but seems it should work on modern Ubuntu too.

**Comment by Smoren** [comment]
Hi @KharLexis,

Thank you for your issue and your idea to solve it! Can you modify the script with if statetement for Ubuntu version, test it on your distr and open a pull request?

**Comment by KharLexis** [comment]
Hi @Smoren, i have tested this method, it works! And i opened pull request. 
@vimmerru Thanks a lot for solution!

**Comment by Smoren** [comment]
@KharLexis, sorry, I do not see your pull request. Can you check it and send the link here?

**Comment by KharLexis** [comment]
> @KharLexis, sorry, I do not see your pull request. Can you check it and send the link here?

https://github.com/Smoren/huawei-ubuntu-sound-fix/compare/master...KharLexis:KharLexis-patch-1?expand=1

**Comment by Smoren** [comment]
@KharLexis, PR is merged. https://github.com/Smoren/huawei-ubuntu-sound-fix/pull/5
Please check on your device.

**Comment by KharLexis** [comment]
> Please check on your device.

Disabled and uninstalled the service, deleted directories, rebooted OS, downloaded the package with the changes, installed. Everything works great!

**Comment by Smoren** [comment]
@KharLexis thank you!

**Comment by Smoren** [comment]
@KharLexis thank you!

**Comment by KharLexis** [comment]
> @KharLexis thank you!

Your welcome!)
