### ISSUE TITLE
Fedora supports & Uninstall script

### ISSUE THREAD

**Issue by maksimetny** [Smoren/huawei-ubuntu-sound-fix#7]
Hi
This fix is works on Fedora 39 for MateBook 14s

I think the following features will be useful for some users:
- Add variant for `dnf` package manager
- Add uninstall script (Removes all fix files and service)

**Comment by Smoren** [comment]
Hi @maksimetny! Thank you for your suggestion! You can implement this features and make a PR.
However, uninstall script has been already added.
